### ISSUE TITLE
Not all class names are being minified

### ISSUE THREAD

**Issue by dwilt** [yiminghe/grunt-class-id-minifier#1]
Code below:

```CSS
.kb-filters-tabs {
    background-color: #cecece
}

.kb-filters-tabs .uni-tab-content, .uni-search-results-filters-tabs .uni-tab-header {
    background-color: #e6e6e6
}

.kb-filters-tabs .uni-tab-header:after, .uni-search-results-filters-tabs .uni-tab-header:before {
    background-color: #2f2e2e
}

.kn, .uni-search-result-department-filter {
    margin-bottom: 16px
}
```

Notice the kb- prefix? It is minifying the first part of the selector, but not the entire thing. It should look something like this:

```CSS
.kbs {
    background-color: #cecece
}

.kbs .dzt, .asf .huh {
    background-color: #e6e6e6
}

.kbs .huh:after, .asf .huh:before {
    background-color: #2f2e2e
}

.kn, .blah {
    margin-bottom: 16px
}
```

See how I replaced all of the non-minified classnames with a random small string. If you have time, I'd love to show you/replicate this for you over a screenshare. Thanks!
